"""
Django settings for library_management_system project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
import dj_database_url
from decouple import config
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG")

ALLOWED_HOSTS = ['*']  

# Application definition
INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.staticfiles",

    'colorfield',
    'admin_interface',

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
  
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",

    'chatbot',
    "accounts",
    "hemronepal",

    'django_celery_beat',
]

ADMIN_INTERFACE = {
    "SITE_TITLE": "hamronepal",
    "SITE_HEADER": "hamronepal",
    "SITE_BRAND": "hamronepal",
}

JAZZMIN_SETTINGS = {
    "site_title": "hamro_nepal",
    "site_header": "hamro_nepal",
    "site_brand": "hamro_nepal",

    "site_logo": "../media/images/m.jpg",
    "login_logo": "../media/images/m.jpg",
    "custom_css": "../media/custom.css",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "accounts.middleware.RefreshCookieToBodyMiddleware",  
    'accounts.middleware.NepalTimezoneMiddleware',
]

ROOT_URLCONF = "hamro_nepal.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hamro_nepal.wsgi.application"

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'hamro_nepal',
        'USER': 'postgres',
        'PASSWORD': 'rudra',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

REDIS_URL = os.environ.get("REDIS_URL")
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'     
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Kathmandu'

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kathmandu"
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

if DEBUG:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "accounts.Users"

# REST Framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.authentication.JWTAuthenticationFromCookie",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

# SIMPLE JWT settings with cookie configuration
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    # Cookie settings for cross-site usage
    "AUTH_COOKIE": "access_token",
    "AUTH_COOKIE_REFRESH": "refresh_token",
    "AUTH_COOKIE_SAMESITE": "None",  # Required for cross-site cookies
    "AUTH_COOKIE_SECURE": True,      # Required with SameSite=None and HTTPS
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_COOKIE_DOMAIN": None,      # Set to None for flexible domain matching
}

# =========================================================
# CORS
# =========================================================

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://cfcf-182-93-68-229.ngrok-free.app",

    # Vercel frontend
    "https://react-frontend-tvl2.vercel.app",

    # Render backend/frontend if applicable
    "https://drf-1-p3vn.onrender.com",

    # VS Code dev tunnel
    "https://sm3j0j49-5173.inc1.devtunnels.ms",
    "https://ns7s5p47-5173.inc1.devtunnels.ms"
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.ngrok-free\.app$",
]

# Explicitly allow headers sent by frontend clients and ngrok
CORS_ALLOW_HEADERS = list(default_headers) + [
    "ngrok-skip-browser-warning",
]

# =========================================================
# CSRF
# =========================================================

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",

    "https://react-frontend-tvl2.vercel.app",

    "https://sm3j0j49-5173.inc1.devtunnels.ms",

    "https://drf-1-p3vn.onrender.com",

    # ngrok
    "https://*.ngrok-free.app",
]
CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = True

SESSION_COOKIE_SAMESITE = "None"
SESSION_COOKIE_SECURE = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'katuwalmadan55@gmail.com'
EMAIL_HOST_PASSWORD = 'lrsa giqa ylhc qgro'

# eSewa Configuration
ESEWA_MERCHANT_CODE = "EPAYTEST"
ESEWA_SECRET_KEY = "8gBm/:&EnhH.1/q"
ESEWA_GATEWAY = "https://rc-epay.esewa.com.np/api/epay/main/v2/form"

ESEWA_SUCCESS_URL = "http://localhost:5173/payment-success"
ESEWA_FAILURE_URL = "http://localhost:5173/payment-failure"

# Vector Database / Chatbot Settings
QDRANT_URL = "http://localhost:6333"
QDRANT_COLLECTION = "library_books"

EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"