# Generated by Django 6.0.2 on 2026-02-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_users_token_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="last_logout",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
