# Generated by Django 5.2.11 on 2026-08-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hemronepal", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="problemreport",
            options={},
        ),
        migrations.AlterField(
            model_name="problemreport",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="problem_reports/%Y/%m/%d/"
            ),
        ),
    ]
