# Generated by Django 5.2.11 on 2026-08-21 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hemronepal", "0004_organizationproblemreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationproblemreport",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="organizationproblemreport",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organizationproblemreport",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organizationproblemreport",
            name="organization",
            field=models.ForeignKey(
                limit_choices_to={"role": "organizer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_problem_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organizationproblemreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("overdue", "Overdue"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
