# Generated by Django 5.2.11 on 2026-08-21 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hemronepal", "0005_alter_organizationproblemreport_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationproblemreport",
            name="organization",
            field=models.ForeignKey(
                limit_choices_to={"Role": "organizer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organization_problem_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
