# Generated by Django 6.0.2 on 2026-02-07 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_admin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"Role__in": ["admin", "employee"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books_added",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
