# Generated by Django 5.2.11 on 2026-02-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "library_admin",
            "0005_alter_book_authors_alter_booktransaction_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcomment",
            name="stars",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Rating out of 5"
            ),
        ),
    ]
