# Generated by Django 5.2.11 on 2026-02-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_admin", "0007_notice_noticeread"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booktransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("issued", "Issued"),
                    ("reserved", "Reserved"),
                    ("returned", "Returned"),
                    ("expired", "expired"),
                ],
                max_length=10,
            ),
        ),
    ]
